Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'apps/api/application.rb'
